image: gitpod/workspace-rust

tasks:
  - name: Install Tools
    init: |
      sudo apt-get update && sudo apt-get install -y binaryen wabt
      cargo install odra-cli --features casper
      rustup target add wasm32-unknown-unknown
    command: |
      echo "Ready to deploy! Create your secret_key.pem file and run: cd staking-tracker && cargo odra deploy -b casper-testnet"

vscode:
  extensions:
    - rust-lang.rust-analyzer
